site_name: SWARM Documentation
site_url: https://comprna.github.io/SWARM/
repo_url: https://github.com/comprna/SWARM
repo_name: comprna/SWARM
docs_dir: docs
site_dir: site
theme:
  name: readthedocs
  highlightjs: true
  hljs_style: github
  font:
    text: Merriweather Sans
    code: Red Hat Mono
nav:
  - Home: index.md
  - Installation: installation.md
  - Preprocessing raw data: preprocessing.md
  - Read-level detection: read_level.md
  - Site-level detection: site_level.md
  - Modification visualization: modbam.md
  - Differential modification analysis: diff_test.md
markdown_extensions:
  - fenced_code
  - codehilite:
      guess_lang: false
      linenums: false
  - attr_list
  - pymdownx.superfences